"""Add ru and uk locales

Revision ID: 2191e1c0945d
Revises: ddb37cbe47f9
Create Date: 2026-06-15 19:46:03.450003

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2191e1c0945d'
down_revision: Union[str, Sequence[str], None] = 'ddb37cbe47f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE languageenum ADD VALUE IF NOT EXISTS 'RU'")
    op.execute("ALTER TYPE languageenum ADD VALUE IF NOT EXISTS 'UK'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
