"""Update enums

Revision ID: 7a802f1f6cf5
Revises: b80926d4bb6e
Create Date: 2026-07-06 20:32:06.599790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a802f1f6cf5'
down_revision: Union[str, Sequence[str], None] = 'b80926d4bb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE permissionsenum RENAME TO permissionenum")
    op.alter_column('users_roles', 'permissions',
               existing_type=postgresql.ARRAY(postgresql.ENUM('DASHBOARD_VIEW', 'DASHBOARD_CPU_VIEW', 'DASHBOARD_RAM_VIEW', 'DASHBOARD_DISK_VIEW', 'DASHBOARD_LOGS_VIEW', 'SERVERS_VIEW', 'SERVERS_CREATE', 'SERVERS_DELETE', 'SERVER_VIEW', 'SERVER_UPDATE', 'SERVER_START', 'SERVER_STOP', 'SERVER_CPU_VIEW', 'SERVER_RAM_VIEW', 'SERVER_LOGS_VIEW', 'SERVER_CONSOLE_EXECUTE', 'SERVER_FILES_VIEW', 'SERVER_FILES_UPDATE', 'SERVER_FILES_DOWNLOAD', 'SERVER_SETTINGS_VIEW', 'SERVER_SETTINGS_UPDATE', 'USERS_VIEW', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'ROLES_VIEW', 'ROLES_CREATE', 'ROLES_UPDATE', 'ROLES_DELETE', 'GAMES_VIEW', 'SETTINGS_CACHE_CLEAR', 'SETTINGS_CONTAINERS_CLEAR', name='permissionsenum')),
               type_=sa.ARRAY(sa.Enum('DASHBOARD_VIEW', 'DASHBOARD_CPU_VIEW', 'DASHBOARD_RAM_VIEW', 'DASHBOARD_DISK_VIEW', 'DASHBOARD_LOGS_VIEW', 'SERVERS_VIEW', 'SERVERS_CREATE', 'SERVERS_DELETE', 'SERVER_VIEW', 'SERVER_UPDATE', 'SERVER_START', 'SERVER_STOP', 'SERVER_CPU_VIEW', 'SERVER_RAM_VIEW', 'SERVER_LOGS_VIEW', 'SERVER_CONSOLE_EXECUTE', 'SERVER_FILES_VIEW', 'SERVER_FILES_UPDATE', 'SERVER_FILES_DOWNLOAD', 'SERVER_SETTINGS_VIEW', 'SERVER_SETTINGS_UPDATE', 'USERS_VIEW', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'ROLES_VIEW', 'ROLES_CREATE', 'ROLES_UPDATE', 'ROLES_DELETE', 'GAMES_VIEW', 'SETTINGS_CACHE_CLEAR', 'SETTINGS_CONTAINERS_CLEAR', name='permissionenum')),
               existing_nullable=False)

    op.execute("ALTER TYPE themeenum RENAME VALUE 'DARK' TO 'COBALT_DARK'")
    op.execute("ALTER TYPE themeenum RENAME VALUE 'LIGHT' TO 'COBALT_LIGHT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE permissionenum RENAME TO permissionsenum")
    op.alter_column('users_roles', 'permissions',
               existing_type=sa.ARRAY(sa.Enum('DASHBOARD_VIEW', 'DASHBOARD_CPU_VIEW', 'DASHBOARD_RAM_VIEW', 'DASHBOARD_DISK_VIEW', 'DASHBOARD_LOGS_VIEW', 'SERVERS_VIEW', 'SERVERS_CREATE', 'SERVERS_DELETE', 'SERVER_VIEW', 'SERVER_UPDATE', 'SERVER_START', 'SERVER_STOP', 'SERVER_CPU_VIEW', 'SERVER_RAM_VIEW', 'SERVER_LOGS_VIEW', 'SERVER_CONSOLE_EXECUTE', 'SERVER_FILES_VIEW', 'SERVER_FILES_UPDATE', 'SERVER_FILES_DOWNLOAD', 'SERVER_SETTINGS_VIEW', 'SERVER_SETTINGS_UPDATE', 'USERS_VIEW', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'ROLES_VIEW', 'ROLES_CREATE', 'ROLES_UPDATE', 'ROLES_DELETE', 'GAMES_VIEW', 'SETTINGS_CACHE_CLEAR', 'SETTINGS_CONTAINERS_CLEAR', name='permissionenum')),
               type_=postgresql.ARRAY(postgresql.ENUM('DASHBOARD_VIEW', 'DASHBOARD_CPU_VIEW', 'DASHBOARD_RAM_VIEW', 'DASHBOARD_DISK_VIEW', 'DASHBOARD_LOGS_VIEW', 'SERVERS_VIEW', 'SERVERS_CREATE', 'SERVERS_DELETE', 'SERVER_VIEW', 'SERVER_UPDATE', 'SERVER_START', 'SERVER_STOP', 'SERVER_CPU_VIEW', 'SERVER_RAM_VIEW', 'SERVER_LOGS_VIEW', 'SERVER_CONSOLE_EXECUTE', 'SERVER_FILES_VIEW', 'SERVER_FILES_UPDATE', 'SERVER_FILES_DOWNLOAD', 'SERVER_SETTINGS_VIEW', 'SERVER_SETTINGS_UPDATE', 'USERS_VIEW', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'ROLES_VIEW', 'ROLES_CREATE', 'ROLES_UPDATE', 'ROLES_DELETE', 'GAMES_VIEW', 'SETTINGS_CACHE_CLEAR', 'SETTINGS_CONTAINERS_CLEAR', name='permissionsenum')),
               existing_nullable=False)

    op.execute("ALTER TYPE themeenum RENAME VALUE 'COBALT_DARK' TO 'DARK'")
    op.execute("ALTER TYPE themeenum RENAME VALUE 'COBALT_LIGHT' TO 'LIGHT'")
    # ### end Alembic commands ###
