"""Update server status enum

Revision ID: a5ea65ee5ef9
Revises: 7a802f1f6cf5
Create Date: 2026-07-09 14:45:48.028288

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a5ea65ee5ef9'
down_revision: Union[str, Sequence[str], None] = '7a802f1f6cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE serverstatusenum RENAME TO serverstateenum")
    op.execute("ALTER TYPE serverstateenum ADD VALUE IF NOT EXISTS 'UPGRADING'")
    op.execute("ALTER TYPE serverstateenum ADD VALUE IF NOT EXISTS 'UPGRADE_FAILED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE serverstateenum RENAME TO serverstatusenum")
    # ### end Alembic commands ###
