"""Add light theme

Revision ID: b80926d4bb6e
Revises: 2191e1c0945d
Create Date: 2026-07-04 17:05:07.142361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80926d4bb6e'
down_revision: Union[str, Sequence[str], None] = '2191e1c0945d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE themeenum ADD VALUE IF NOT EXISTS 'LIGHT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
