"""First migration

Revision ID: ddb37cbe47f9
Revises: 
Create Date: 2026-04-19 20:31:00.531939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddb37cbe47f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.Enum('DASHBOARD_VIEW', 'DASHBOARD_CPU_VIEW', 'DASHBOARD_RAM_VIEW', 'DASHBOARD_DISK_VIEW', 'DASHBOARD_LOGS_VIEW', 'SERVERS_VIEW', 'SERVERS_CREATE', 'SERVERS_DELETE', 'SERVER_VIEW', 'SERVER_UPDATE', 'SERVER_START', 'SERVER_STOP', 'SERVER_CPU_VIEW', 'SERVER_RAM_VIEW', 'SERVER_LOGS_VIEW', 'SERVER_CONSOLE_EXECUTE', 'SERVER_FILES_VIEW', 'SERVER_FILES_UPDATE', 'SERVER_FILES_DOWNLOAD', 'SERVER_SETTINGS_VIEW', 'SERVER_SETTINGS_UPDATE', 'USERS_VIEW', 'USERS_CREATE', 'USERS_UPDATE', 'USERS_DELETE', 'ROLES_VIEW', 'ROLES_CREATE', 'ROLES_UPDATE', 'ROLES_DELETE', 'GAMES_VIEW', 'SETTINGS_CACHE_CLEAR', 'SETTINGS_CONTAINERS_CLEAR', name='permissionsenum')), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games_loaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_game_id_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('loader_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'CREATED', 'FAILED', name='serverstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loader_id'], ['games_loaders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('EN', name='languageenum'), nullable=False),
    sa.Column('theme', sa.Enum('DARK', name='themeenum'), nullable=False),
    sa.Column('timezone', sa.Enum('UTC_MINUS_12', 'UTC_MINUS_11', 'UTC_MINUS_10', 'UTC_MINUS_9', 'UTC_MINUS_8', 'UTC_MINUS_7', 'UTC_MINUS_6', 'UTC_MINUS_5', 'UTC_MINUS_4', 'UTC_MINUS_3', 'UTC_MINUS_2', 'UTC_MINUS_1', 'UTC', 'UTC_PLUS_1', 'UTC_PLUS_2', 'UTC_PLUS_3', 'UTC_PLUS_4', 'UTC_PLUS_5', 'UTC_PLUS_6', 'UTC_PLUS_7', 'UTC_PLUS_8', 'UTC_PLUS_9', 'UTC_PLUS_10', 'UTC_PLUS_11', 'UTC_PLUS_12', name='timezoneenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.execute("""
        CREATE OR REPLACE FUNCTION prevent_direct_settings_delete()
        RETURNS TRIGGER AS $$
        BEGIN
            IF EXISTS (SELECT 1 FROM users WHERE id = OLD.user_id) THEN
                RAISE EXCEPTION 'Direct deletion of user settings is not allowed.';
            END IF;
            RETURN OLD;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE OR REPLACE TRIGGER no_direct_settings_delete
        BEFORE DELETE ON users_settings
        FOR EACH ROW EXECUTE FUNCTION prevent_direct_settings_delete();
    """)
    op.create_table('servers_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'key', name='uq_server_id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers_attributes')
    op.execute("DROP TRIGGER IF EXISTS no_direct_settings_delete ON users_settings;")
    op.execute("DROP FUNCTION IF EXISTS prevent_direct_settings_delete;")
    op.drop_table('users_settings')
    op.drop_table('servers')
    op.drop_table('users')
    op.drop_table('games_loaders')
    op.drop_table('users_roles')
    op.drop_table('games')
    # ### end Alembic commands ###
